### ISSUE TITLE
As is score not visible when setting the score in alternative section

### ISSUE THREAD

**Issue by vsjoberg** [ecodistrict/IDSSDashboard#151] opened 2016-02-17 14:05 UTC
Once you have created the KPI and you set the score in the as is it is fine. Then you move on to setting the ambiton and then when you click the alternatives you see a dark grey indicator which shows the as is-score. But if you go out of that screen and back again it is gone.

**Comment by andreasrudena** [comment] 2016-02-24 10:49
This could have been fixed during the previous updates, I cannot reproduce it now. So, I will close the issue, and you can reopen it again if you can find the problem.

**Closed by andreasrudena** 2016-02-24 10:49 UTC
