### ISSUE TITLE
Ambitions get set for new stakeholder

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#133] opened 2015-09-18 07:29 UTC
E.g. logging in as

Name: Havensteder, Email: havensteder@rubroek.ed, Password: warande

The ambitions are already there for the 'old' KPI's. None of them should be set for a new stakeholder.

**Comment by andreasrudena** [comment] 2015-09-18 09:12
This is probably from old data - a version in the dashboard when values was taken from facilitator. When adding a new KPI, I could not reproduce this. So the solution would be to enter the stakeholder account to remove the ambitions (enter an empty value). Does this work?

**Comment by andreasrudena** [comment] 2015-10-13 07:52
Close this for now, if problems still occur, reopen!

**Closed by andreasrudena** 2015-10-13 07:52 UTC
Labels: bug, enhancement, prio 1 (highest), Required for Rubroek
